### ISSUE TITLE
Matomo DB restarts

### ISSUE THREAD

**Issue by Happyfeet01** [bitnami/bitnami-docker-matomo#32]
**Description**

Hello, it try to Setup Matomo with an Password for the Database, but it won`t work, whats wrong with my Setup?

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:11:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:59:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 34
 Running: 32
 Paused: 0
 Stopped: 2
Images: 38
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-52-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: larsmueller.net
ID: 6GIK:W6PR:6SYB:N5KK:3HOD:KNSV:FERA:VT2O:DO7B:BFJF:NJBG:RPYX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

Docker-compose log:

```
root@larsmueller:/docker/matomo# docker-compose up
Creating network "matomo_default" with the default driver
Creating matomo_mariadb_1 ... done
Creating matomo_application_1 ... done
Attaching to matomo_mariadb_1, matomo_application_1
application_1  | 
mariadb_1      | 
application_1  | Welcome to the Bitnami matomo container
mariadb_1      | Welcome to the Bitnami mariadb container
application_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
mariadb_1      | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
application_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
mariadb_1      | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
application_1  | 
mariadb_1      | Send us your feedback at containers@bitnami.com
mariadb_1      | 
mariadb_1      | 
application_1  | nami    INFO  Initializing apache
application_1  | nami    INFO  apache successfully initialized
matomo_mariadb_1 exited with code 0
application_1  | nami    INFO  Initializing php
application_1  | nami    INFO  php successfully initialized
application_1  | nami    INFO  Initializing mysql-client
application_1  | nami    INFO  mysql-client successfully initialized
application_1  | nami    INFO  Initializing matomo
matomo_mariadb_1 exited with code 0
Exception in thread Thread-7:
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.22/containers/fd0b0a8a94ce1e80d399f7aa148b7c9468e0a65d71045ae381c0a343699be48c/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 233, in watch_events
  File "compose/container.py", line 215, in attach_log_stream
  File "compose/container.py", line 307, in attach
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 61, in attach
  File "site-packages/docker/api/client.py", line 400, in _read_from_socket
  File "site-packages/docker/api/client.py", line 311, in _get_raw_response_socket
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error: Conflict ("b'container fd0b0a8a94ce1e80d399f7aa148b7c9468e0a65d71045ae381c0a343699be48c is restarting, wait until the container is running'")

application_1  | matomo  INFO  Preparing PHP environment...
application_1  | matomo  INFO  Preparing matomo environment...
application_1  | mysql-c INFO  Trying to connect to MySQL server
```

Docker-compose.yml

```
version: '2'

services:
  mariadb:
    user: root
    command: chown -R 1001:1001 /bitnami/mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=V2STwbtkasZrZfj9M
      - MYSQL_DATABASE_NAME=bitnami_matomo
      - MYSQL_DATABASE_USER=adzztfzs_matomo
      - MYSQL_DATABASE_PASSWORD=tSsxrkcnF3rTNA4v9
    volumes:
      - '/home/matomo/mariadb_data:/bitnami/mariadb'
    restart: always
  application:
    image: 'bitnami/matomo:latest'
    environment:
      - MATOMO_USERNAME=suer
      - MATOMO_PASSWORD=password
      - MATOMO_EMAIL=server@domain.tld
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=adzztfzs_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - MATOMO_DATABASE_PASSWORD=tSsxrkcnF3rTNA4v9
    ports:
      - '8087:80'
      - '4446:443'
    volumes:
      - '/home/matomo/matomo_data:/bitnami'
    depends_on:
      - mariadb
    restart: always

volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
```

**Comment by tompizmor** [comment]
Hi,

You are overriding the startup command for the MariaDB container so the server is never starting. 

Apart from that, the environment variables for the MariaDB container are wrong. Please use this docker-compose file below:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=V2STwbtkasZrZfj9M
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_USER=adzztfzs_matomo
      - MARIADB_PASSWORD=tSsxrkcnF3rTNA4v9
    volumes:
      - '/home/matomo/mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/matomo:latest'
    environment:
      - MATOMO_USERNAME=suer
      - MATOMO_PASSWORD=password
      - MATOMO_EMAIL=server@domain.tld
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=adzztfzs_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - MATOMO_DATABASE_PASSWORD=tSsxrkcnF3rTNA4v9
    ports:
      - '8087:80'
      - '4446:443'
    volumes:
      - '/home/matomo/matomo_data:/bitnami'
    depends_on:
      - mariadb
```

Please note that as you are mounting a local folder for MariaDB and MariaDB is a non-root container you need to change the permissions of your local folder before deploying the containers.

```
sudo chown -R 1001:1001 /home/matomo/
```

**Comment by Happyfeet01** [comment]
Thanks it works
