### ISSUE TITLE
Since the latest update,? No Stats

### ISSUE THREAD

**Issue by Happyfeet01** [bitnami/bitnami-docker-matomo#35]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

Since the latest update, no stats displayed. But in container logs the website visited are available. 

**Describe the results you expected:**

see the stats again at the webui

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 32
 Running: 32
 Paused: 0
 Stopped: 0
Images: 70
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-55-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: larsmueller.net
ID: 6GIK:W6PR:6SYB:N5KK:3HOD:KNSV:FERA:VT2O:DO7B:BFJF:NJBG:RPYX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker logs
```
[Thu Jul 25 21:35:55.169787 2019] [php7:error] [pid 124] [client 172.18.0.1:35184] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Piwik\\Tracker\\GoalManager::detectGoalsMatchingUrl(), 2 passed in /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php on line 92 and exactly 4 expected in /opt/bitnami/matomo/core/Tracker/GoalManager.php:131\nStack trace:\n#0 /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php(92): Piwik\\Tracker\\GoalManager->detectGoalsMatchingUrl(2, Object(Piwik\\Tracker\\ActionPageview))\n#1 /opt/bitnami/matomo/core/Tracker/Visit.php(152): Piwik\\Plugins\\Goals\\Tracker\\GoalsRequestProcessor->afterRequestProcessed(Object(Piwik\\Tracker\\Visit\\VisitProperties), Object(Piwik\\Tracker\\Request))\n#2 /opt/bitnami/matomo/core/Tracker.php(138): Piwik\\Tracker\\Visit->handle()\n#3 /opt/bitnami/matomo/core/Tracker/Handler.php(49): Piwik\\Tracker->trackRequest(Object(Piwik\\Tracker\\Request))\n#4 /opt/bitnami/matomo/core/Tracker.php(120): Piwik\\Tracker\\Handler->process(Object(Piwik\\Tracker), Object(Piwik\\Tracker\\RequestSet))\n#5 /opt/bitnami/matomo/core/Tracker.php(97): Pi in /opt/bitnami/matomo/core/Tracker/GoalManager.php on line 131, referer: https://dasnetzundich.de/howto-pihole-auf-dem-odroid-c2-installieren/
172.18.0.1 - - [25/Jul/2019:21:35:54 +0000] "GET /matomo.php?action_name=%5BHowto%5D%20Pihole%20auf%20dem%20Odroid%20C2%20installieren%20%E2%80%93%20dasnetzundich.de&idsite=2&rec=1&r=810137&h=23&m=35&s=54&url=https%3A%2F%2Fdasnetzundich.de%2Fhowto-pihole-auf-dem-odroid-c2-installieren%2F&urlref=https%3A%2F%2Fwww.google.com%2F&_id=f2574987d5f65b0b&_idts=1564090555&_idvc=1&_idn=0&_refts=1564090555&_viewts=1564090555&_ref=https%3A%2F%2Fwww.google.com%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=1&res=1280x800&gt_ms=1655&pv_id=ObOQNb HTTP/1.0" 500 -
172.18.0.1 - - [25/Jul/2019:21:36:06 +0000] "GET / HTTP/1.0" 200 13312
172.18.0.1 - - [25/Jul/2019:21:44:18 +0000] "POST / HTTP/1.0" 200 806
172.18.0.1 - - [25/Jul/2019:21:46:37 +0000] "POST / HTTP/1.0" 200 806
172.18.0.1 - - [25/Jul/2019:21:48:42 +0000] "POST / HTTP/1.0" 200 806
```

**Comment by andresbono** [comment]
Hi @Happyfeet01, can you share a screenshot of the expected and actual results?

Do you think the issue is related to how Matomo is configured or maybe it is just that last versions of Matomo disabled that functionality?

**Comment by Happyfeet01** [comment]
Since the latest update I have this error. But now I get other permission errors after recreate the container.

**Comment by Happyfeet01** [comment]
Now i get this at the container log 

```
Welcome to the Bitnami matomo container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues

nami    INFO  Initializing matomo
matomo  INFO  Preparing PHP environment...
matomo  INFO  matomo has being already initialized, restoring...
Error executing 'postInstallation': The installation of Matomo failed.
```

**Comment by Laul0** [comment]
Same issue here: https://github.com/matomo-org/matomo/issues/14698#issuecomment-515454606

**Comment by Laul0** [comment]
This is exactly what I did to fix it once connected to the container:

```bash
cd /opt/bitnami
apt-get update
apt-get install unzip
apt-get install wget
cp ./matomo/config/config.ini.php ./
wget https://builds.matomo.org/matomo.zip
unzip -o matomo.zip
rm matomo.zip
```

> The config file was not overwrited and Matomo worked directly

**Comment by andresbono** [comment]
Thanks for sharing your solution, @Laul0.
