### ISSUE TITLE
Migration to 4.0.5 failed

### ISSUE THREAD

**Issue by Laul0** [bitnami/bitnami-docker-matomo#67]
**Description**

Upgrade Matomo 3.1.14 to 4.0.5

**Steps to reproduce the issue:**

1. docker-compose -f matomo-composer.yml pull
2. docker-compose -f matomo-composer.yml up -d

**Describe the results you received:**

Database migration seems OK (no error) after manually fixed the below issues.

Severals error fixed manually:
- rsync error permissions (chown 1001:1001)
- Error CRON cannot be launch because user is not root and RSYNC not permitted (cool no root container, but...). Add into the composer file:
  ```
  user: root
  ```
  > Still root finally...
- Force virtual port to 8080 because the previous version seems work with port 80
- Tag Manager lost all data.... deactivate module and enabled it again and OK
- Launch the command `/opt/bitnami/matomo/console core:convert-to-utf8mb4` does not work if you did not allow execution on console (chown +R /opt/bitnami/matomo/console)
- Now, new problem and I did not found a solution:
```
[Wed Dec 09 21:35:56.889261 2020] [php7:error] [pid 156] [client IP:38390] PHP Fatal error:  Uncaught Error: Call to undefined method Piwik\\Tracker\\Request::getDaysSinceLastVisit() in /bitnami/matomo/plugins/VisitorInterest/Columns/VisitsByDaysSinceLastVisit.php:38\nStack trace:\n#0 /opt/bitnami/matomo/core/Tracker/Visit.php(499): Piwik\\Plugins\\VisitorInterest\\Columns\\VisitsByDaysSinceLastVisit->onNewVisit(Object(Piwik\\Tracker\\Request), Object(Piwik\\Tracker\\Visitor), Object(Piwik\\Tracker\\ActionPageview))\n#1 /opt/bitnami/matomo/core/Tracker/Visit.php(302): Piwik\\Tracker\\Visit->triggerHookOnDimensions(Array, 'onNewVisit')\n#2 /opt/bitnami/matomo/core/Tracker/Visit.php(209): Piwik\\Tracker\\Visit->handleNewVisit(NULL)\n#3 /opt/bitnami/matomo/core/Tracker.php(160): Piwik\\Tracker\\Visit->handle()\n#4 /opt/bitnami/matomo/core/Tracker/Handler.php(55): Piwik\\Tracker->trackRequest(Object(Piwik\\Tracker\\Request))\n#5 /opt/bitnami/matomo/core/Tracker.php(140): Piwik\\Tracker\\Handler->process(Object(Piwik\\Tracker), Object(Piwik\\Tracker\\RequestSet))\n#6 /opt/bitnami/matomo/core/Tracker.php(115): Piwik\\Tracker->track(Object(P in /bitnami/matomo/plugins/VisitorInterest/Columns/VisitsByDaysSinceLastVisit.php on line 38, referer: https://mywebsitepage.url/,
IP- - [09/Dec/2020:21:35:55 +0000] "POST /piwik.php?ping=1&idsite=1&rec=1&r=079328&h=16&m=35&s=55&url=https%3A%2F%2Fmywebsitepage.url%2F&_id=c7252c2e63bfe0cd&_idn=0&_refts=1607548484&_ref=https%3A%2F%2Fwww.bing.com%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=2560x1440&pf_net=0&pf_srv=475&pf_tfr=328&pf_dm1=330&pf_dm2=104&pf_onl=11&pv_id=JYpZq3 HTTP/1.1" 204 -,
IP - - [09/Dec/2020:21:35:56 +0000] "POST /piwik.php?action_name=MyPageName&idsite=[trackingId]&rec=1&r=814855&h=16&m=35&s=56&url=https%3A%2F%2Fmywebsitepage.url%2F&_id=c7252c2e63bfe0cd&_idn=0&_refts=1607548484&_ref=https%3A%2F%2Fwww.bing.com%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=2560x1440&pv_id=zl8VBO&pf_net=0&pf_srv=360&pf_tfr=317&pf_dm1=406&pf_dm2=156&pf_onl=5 HTTP/1.1" 500 -
```

**Describe the results you expected:**

After migration, everything works like before :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
18.09.5
```

- Output of `docker info`:

```
Containers: xxx
 Running: xxx
 Paused: 0
 Stopped: xx
Images: xxx
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 256GiB
Name: servername
ID: ???
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Laul0** [comment]
Ok, I finally fix it by deleting the plugins folder, dow and up again the container

**Comment by dani8art** [comment]
Hi @Laul0 good to hear you fixed it!

Please, don't hesitate to contact us if you find any other issues
